select * from gold.dim_customers
select * from gold.dim_products
select * from gold.fact_sales

--explore All Ojects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore All Columns in the Database.
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dim_customers'

--Explore All Countries our customers come from

SELECT DISTINCT
country from gold.dim_customers

-- Explore All Product Categories "The Major Divisions".

select distinct category,subcategory,product_name from gold.dim_products
order by 1,2,3;
--DATE EXPLORATION:
--find the date of the first and last order
--How many years of sales are avaiable
SELECT MIN(order_date) AS FIRST_ORDER_DATE ,
MAX(order_date) AS last_order_date,
DATEDIFF(year,MIN(order_date),max(order_date)) as order_range_months
from gold.fact_sales

--Find the youngest and oldest customer

select min(birthdate) as oldest_birthdate,
datediff(year,min(birthdate),GETDATE()) AS oldest_age,
MAX(birthdate) as youngest_birthdate,
datediff(year,max(birthdate),GETDATE()) AS YOUNGEST_AGE
FROM gold.dim_customers

--4)MEASURE EXPLORATION
--Find the Total Sales
	SELECT SUM(sales_amount) as total_sales from gold.fact_sales
--Find how many items are sold
	SELECT SUM(quantity) as total_quantity from gold.fact_sales
--find the average selling price
	SELECT AVG(price) as avg_price from gold.fact_sales
--Find the total number of Orders
	SELECT COUNT(order_number) as total_orders from gold.fact_sales
	SELECT COUNT(DISTINCT order_number) as total_orders from gold.fact_sales
--Find the total numbers of products
	SELECT COUNT(product_name) as total_products from gold.dim_products
	SELECT COUNT(DISTINCT product_name) as total_products from gold.dim_products
--Find the Total number of Customers
	SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers
--Find the Total number of Customers that has placed an order
	SELECT COUNT(customer_id) AS total_customers FROM gold.fact_sales;

--Generate a Report that Shows all key metrices of the business

	SELECT 'TOTAL SALES' AS measure_name ,SUM(sales_amount) as measure_values  from gold.fact_sales
	union all
	SELECT 'Total Quantity',SUM(quantity)  from gold.fact_sales
	union all
	SELECT 'Average Price', AVG(price)  from gold.fact_sales
	union all
	SELECT 'Total Nr.Orders',COUNT(DISTINCT order_number)  from gold.fact_sales
	union all
	SELECT 'Total Nr.Products', COUNT(DISTINCT product_name) from gold.dim_products
	union all
	SELECT 'Total Nr.Customers', COUNT(customer_key)  FROM gold.dim_customers;

	--Magnitude Analysis

--Find total customers by countries
	select country,count(customer_key) as total_customers
	from gold.dim_customers
	group by country
	order by 2 desc;
--Find total customers by gender
	select gender,count(customer_key) as total_gender
	from gold.dim_customers
	group by gender
	order by 2 desc;

--Find total products by category
	select category,count(product_key) as total_products
	from gold.dim_products
	group by category
	order by 2 desc;

--What is the average costs in each category?
	select category,AVG(COST) as AVG_COST
	from gold.dim_products
	group by category
	order by 2 desc;


--What is the total revenue generated for each category?
	select sum(f.sales_amount) as total_revenue,p.category
	from gold.fact_sales f
	left join gold.dim_products p
	on p.product_key=f.product_key
	GROUP BY p.category
	order by total_revenue desc

--Find total revenue is generated by each customer
	select c.customer_key,c.first_name,c.last_name, sum(f.sales_amount) as total_revenue
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_key=f.customer_key
	group by c.customer_key,
	c.first_name,c.last_name
	order by total_revenue desc
--What is the distribution of sold items across countries?
	select c.country,
	sum(f.quantity) as total_sold_items
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_id=f.customer_id
	group by c.country
	order by total_sold_items desc
--select * from gold.fact_sales
--select * from gold.dim_customers

--6)Ranking Analysis
--Which 5 products generate the highest revenue
select top 5 p.product_name,
SUM(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue desc

--What are the 5 worst-performong products in terms of Sales
select top 5 p.product_name,
SUM(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue 
